<a href="https://colab.research.google.com/github/pedroyepiz/PYTHON-2023-1/blob/main/11_abril_2025.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NEMPL
AREA
NOMBRE APPAT APMAT
EDAD
SEXO

In [53]:
import random
import pandas as pd
import yaml

In [12]:
def gendicc():
    nom_h =["MARTIN","EMANUEL","PAULO","OSCAR","YAZBEK","PEDRO","CARLOS","GILBERTO"]
    nom_m =["KARINA","PAUILINA","MANUELA","CARLOTA","PETRA"]
    ape =["MARIN","KHALIFA","YEPIZ","GAYNOR","BARBOSA","GARCIA","MORALES","ROMERO","SANCHEZ","MAVRIRIS","FLORES"]
    area = ["SUPERVISOR","GERENTE","PRODUCCION","QA","ALMACEN","SISTEMAS","OFICINA"]

    datos = []
    datos.append(random.randrange(1,500))
    datos.append(random.choice(ape))
    datos.append(random.choice(ape))
    sex = random.choice(["HOMBRE","MUJER"])
    if sex == "HOMBRE":
        datos.append(random.choice(nom_h))
    else:
        datos.append(random.choice(nom_m))
    datos.append(random.choice(area))
    datos.append(sex)
    datos.append(random.randrange(18,65))
    return tuple(datos)

In [44]:
lista =[]

In [51]:
claves = ["num_emp","ap_pat","ap,mat","nombre","area","sexo","edad"]

for i in range(10):
    valores = gendicc()
    reg = dict(zip(claves,valores))
    lista.append(reg)
print(lista)

[{'num_emp': 16, 'ap_pat': 'SANCHEZ', 'ap,mat': 'GAYNOR', 'nombre': 'GILBERTO', 'area': 'ALMACEN', 'sexo': 'HOMBRE', 'edad': 28}, {'num_emp': 322, 'ap_pat': 'SANCHEZ', 'ap,mat': 'KHALIFA', 'nombre': 'PAULO', 'area': 'QA', 'sexo': 'HOMBRE', 'edad': 60}, {'num_emp': 183, 'ap_pat': 'ROMERO', 'ap,mat': 'KHALIFA', 'nombre': 'GILBERTO', 'area': 'GERENTE', 'sexo': 'HOMBRE', 'edad': 31}, {'num_emp': 252, 'ap_pat': 'FLORES', 'ap,mat': 'MAVRIRIS', 'nombre': 'EMANUEL', 'area': 'ALMACEN', 'sexo': 'HOMBRE', 'edad': 25}, {'num_emp': 353, 'ap_pat': 'GAYNOR', 'ap,mat': 'MORALES', 'nombre': 'YAZBEK', 'area': 'GERENTE', 'sexo': 'HOMBRE', 'edad': 50}, {'num_emp': 78, 'ap_pat': 'MARIN', 'ap,mat': 'GARCIA', 'nombre': 'OSCAR', 'area': 'GERENTE', 'sexo': 'HOMBRE', 'edad': 43}, {'num_emp': 24, 'ap_pat': 'GAYNOR', 'ap,mat': 'YEPIZ', 'nombre': 'PEDRO', 'area': 'OFICINA', 'sexo': 'HOMBRE', 'edad': 27}, {'num_emp': 367, 'ap_pat': 'YEPIZ', 'ap,mat': 'GAYNOR', 'nombre': 'MANUELA', 'area': 'SISTEMAS', 'sexo': 'MUJER', 'edad': 39}, {'num_emp': 275, 'ap_pat': 'GARCIA', 'ap,mat': 'GAYNOR', 'nombre': 'KARINA', 'area': 'SISTEMAS', 'sexo': 'MUJER', 'edad': 40}, {'num_emp': 39, 'ap_pat': 'MORALES', 'ap,mat': 'MARIN', 'nombre': 'EMANUEL', 'area': 'QA', 'sexo': 'HOMBRE', 'edad': 62}, {'num_emp': 38, 'ap_pat': 'KHALIFA', 'ap,mat': 'MARIN', 'nombre': 'CARLOTA', 'area': 'SUPERVISOR', 'sexo': 'MUJER', 'edad': 19}, {'num_emp': 51, 'ap_pat': 'FLORES', 'ap,mat': 'SANCHEZ', 'nombre': 'CARLOTA', 'area': 'SISTEMAS', 'sexo': 'MUJER', 'edad': 18}, {'num_emp': 163, 'ap_pat': 'KHALIFA', 'ap,mat': 'GARCIA', 'nombre': 'MARTIN', 'area': 'SUPERVISOR', 'sexo': 'HOMBRE', 'edad': 57}, {'num_emp': 4, 'ap_pat': 'BARBOSA', 'ap,mat': 'BARBOSA', 'nombre': 'MANUELA', 'area': 'PRODUCCION', 'sexo': 'MUJER', 'edad': 34}, {'num_emp': 197, 'ap_pat': 'MAVRIRIS', 'ap,mat': 'SANCHEZ', 'nombre': 'PEDRO', 'area': 'GERENTE', 'sexo': 'HOMBRE', 'edad': 41}, {'num_emp': 205, 'ap_pat': 'YEPIZ', 'ap,mat': 'MORALES', 'nombre': 'PETRA', 'area': 'PRODUCCION', 'sexo': 'MUJER', 'edad': 20}, {'num_emp': 70, 'ap_pat': 'MARIN', 'ap,mat': 'ROMERO', 'nombre': 'PAULO', 'area': 'QA', 'sexo': 'HOMBRE', 'edad': 54}, {'num_emp': 346, 'ap_pat': 'SANCHEZ', 'ap,mat': 'GARCIA', 'nombre': 'CARLOS', 'area': 'GERENTE', 'sexo': 'HOMBRE', 'edad': 38}, {'num_emp': 64, 'ap_pat': 'MORALES', 'ap,mat': 'SANCHEZ', 'nombre': 'MANUELA', 'area': 'QA', 'sexo': 'MUJER', 'edad': 57}, {'num_emp': 380, 'ap_pat': 'GARCIA', 'ap,mat': 'GARCIA', 'nombre': 'CARLOS', 'area': 'SUPERVISOR', 'sexo': 'HOMBRE', 'edad': 54}, {'num_emp': 132, 'ap_pat': 'MORALES', 'ap,mat': 'BARBOSA', 'nombre': 'PAUILINA', 'area': 'SUPERVISOR', 'sexo': 'MUJER', 'edad': 20}, {'num_emp': 39, 'ap_pat': 'BARBOSA', 'ap,mat': 'MAVRIRIS', 'nombre': 'CARLOTA', 'area': 'ALMACEN', 'sexo': 'MUJER', 'edad': 27}, {'num_emp': 30, 'ap_pat': 'MAVRIRIS', 'ap,mat': 'MORALES', 'nombre': 'KARINA', 'area': 'SISTEMAS', 'sexo': 'MUJER', 'edad': 22}, {'num_emp': 222, 'ap_pat': 'SANCHEZ', 'ap,mat': 'FLORES', 'nombre': 'CARLOS', 'area': 'OFICINA', 'sexo': 'HOMBRE', 'edad': 26}, {'num_emp': 146, 'ap_pat': 'SANCHEZ', 'ap,mat': 'YEPIZ', 'nombre': 'PETRA', 'area': 'SUPERVISOR', 'sexo': 'MUJER', 'edad': 45}, {'num_emp': 131, 'ap_pat': 'MORALES', 'ap,mat': 'BARBOSA', 'nombre': 'CARLOTA', 'area': 'OFICINA', 'sexo': 'MUJER', 'edad': 42}, {'num_emp': 87, 'ap_pat': 'MARIN', 'ap,mat': 'SANCHEZ', 'nombre': 'CARLOS', 'area': 'SUPERVISOR', 'sexo': 'HOMBRE', 'edad': 37}, {'num_emp': 27, 'ap_pat': 'SANCHEZ', 'ap,mat': 'YEPIZ', 'nombre': 'MANUELA', 'area': 'QA', 'sexo': 'MUJER', 'edad': 53}, {'num_emp': 321, 'ap_pat': 'KHALIFA', 'ap,mat': 'MAVRIRIS', 'nombre': 'PETRA', 'area': 'SUPERVISOR', 'sexo': 'MUJER', 'edad': 27}, {'num_emp': 125, 'ap_pat': 'MAVRIRIS', 'ap,mat': 'KHALIFA', 'nombre': 'GILBERTO', 'area': 'PRODUCCION', 'sexo': 'HOMBRE', 'edad': 59}, {'num_emp': 154, 'ap_pat': 'ROMERO', 'ap,mat': 'GAYNOR', 'nombre': 'OSCAR', 'area': 'QA', 'sexo': 'HOMBRE', 'edad': 57}, {'num_emp': 281, 'ap_pat': 'MAVRIRIS', 'ap,mat': 'BARBOSA', 'nombre': 'MANUELA', 'area': 'GERENTE', 'sexo': 'MUJER', 'edad': 46}, {'num_emp': 396, 'ap_pat': 'MARIN', 'ap,mat': 'GAYNOR', 'nombre': 'OSCAR', 'area': 'SISTEMAS', 'sexo': 'HOMBRE', 'edad': 37}, {'num_emp': 358, 'ap_pat': 'ROMERO', 'ap,mat': 'KHALIFA', 'nombre': 'GILBERTO', 'area': 'ALMACEN', 'sexo': 'HOMBRE', 'edad': 37}, {'num_emp': 284, 'ap_pat': 'GAYNOR', 'ap,mat': 'BARBOSA', 'nombre': 'OSCAR', 'area': 'OFICINA', 'sexo': 'HOMBRE', 'edad': 30}, {'num_emp': 176, 'ap_pat': 'KHALIFA', 'ap,mat': 'SANCHEZ', 'nombre': 'OSCAR', 'area': 'ALMACEN', 'sexo': 'HOMBRE', 'edad': 50}, {'num_emp': 339, 'ap_pat': 'GARCIA', 'ap,mat': 'GARCIA', 'nombre': 'MANUELA', 'area': 'PRODUCCION', 'sexo': 'MUJER', 'edad': 23}, {'num_emp': 201, 'ap_pat': 'MAVRIRIS', 'ap,mat': 'MARIN', 'nombre': 'MARTIN', 'area': 'SUPERVISOR', 'sexo': 'HOMBRE', 'edad': 39}, {'num_emp': 306, 'ap_pat': 'GARCIA', 'ap,mat': 'KHALIFA', 'nombre': 'YAZBEK', 'area': 'SISTEMAS', 'sexo': 'HOMBRE', 'edad': 37}, {'num_emp': 403, 'ap_pat': 'GAYNOR', 'ap,mat': 'FLORES', 'nombre': 'OSCAR', 'area': 'ALMACEN', 'sexo': 'HOMBRE', 'edad': 60}, {'num_emp': 154, 'ap_pat': 'MAVRIRIS', 'ap,mat': 'ROMERO', 'nombre': 'CARLOS', 'area': 'GERENTE', 'sexo': 'HOMBRE', 'edad': 44}, {'num_emp': 224, 'ap_pat': 'MORALES', 'ap,mat': 'SANCHEZ', 'nombre': 'KARINA', 'area': 'PRODUCCION', 'sexo': 'MUJER', 'edad': 54}, {'num_emp': 411, 'ap_pat': 'FLORES', 'ap,mat': 'YEPIZ', 'nombre': 'KARINA', 'area': 'SISTEMAS', 'sexo': 'MUJER', 'edad': 35}, {'num_emp': 124, 'ap_pat': 'MORALES', 'ap,mat': 'YEPIZ', 'nombre': 'OSCAR', 'area': 'GERENTE', 'sexo': 'HOMBRE', 'edad': 50}, {'num_emp': 216, 'ap_pat': 'YEPIZ', 'ap,mat': 'MORALES', 'nombre': 'CARLOTA', 'area': 'ALMACEN', 'sexo': 'MUJER', 'edad': 52}, {'num_emp': 207, 'ap_pat': 'YEPIZ', 'ap,mat': 'SANCHEZ', 'nombre': 'MARTIN', 'area': 'GERENTE', 'sexo': 'HOMBRE', 'edad': 50}, {'num_emp': 35, 'ap_pat': 'MARIN', 'ap,mat': 'MARIN', 'nombre': 'CARLOS', 'area': 'SUPERVISOR', 'sexo': 'HOMBRE', 'edad': 55}, {'num_emp': 241, 'ap_pat': 'YEPIZ', 'ap,mat': 'ROMERO', 'nombre': 'MANUELA', 'area': 'PRODUCCION', 'sexo': 'MUJER', 'edad': 38}, {'num_emp': 397, 'ap_pat': 'MARIN', 'ap,mat': 'KHALIFA', 'nombre': 'PEDRO', 'area': 'GERENTE', 'sexo': 'HOMBRE', 'edad': 28}, {'num_emp': 161, 'ap_pat': 'MAVRIRIS', 'ap,mat': 'GAYNOR', 'nombre': 'MANUELA', 'area': 'SUPERVISOR', 'sexo': 'MUJER', 'edad': 31}, {'num_emp': 423, 'ap_pat': 'GAYNOR', 'ap,mat': 'FLORES', 'nombre': 'EMANUEL', 'area': 'OFICINA', 'sexo': 'HOMBRE', 'edad': 38}, {'num_emp': 206, 'ap_pat': 'MAVRIRIS', 'ap,mat': 'ROMERO', 'nombre': 'CARLOS', 'area': 'QA', 'sexo': 'HOMBRE', 'edad': 22}, {'num_emp': 425, 'ap_pat': 'FLORES', 'ap,mat': 'KHALIFA', 'nombre': 'CARLOS', 'area': 'SUPERVISOR', 'sexo': 'HOMBRE', 'edad': 62}, {'num_emp': 57, 'ap_pat': 'SANCHEZ', 'ap,mat': 'FLORES', 'nombre': 'EMANUEL', 'area': 'OFICINA', 'sexo': 'HOMBRE', 'edad': 40}, {'num_emp': 497, 'ap_pat': 'KHALIFA', 'ap,mat': 'YEPIZ', 'nombre': 'GILBERTO', 'area': 'ALMACEN', 'sexo': 'HOMBRE', 'edad': 32}, {'num_emp': 25, 'ap_pat': 'MORALES', 'ap,mat': 'YEPIZ', 'nombre': 'MARTIN', 'area': 'QA', 'sexo': 'HOMBRE', 'edad': 61}, {'num_emp': 203, 'ap_pat': 'SANCHEZ', 'ap,mat': 'MARIN', 'nombre': 'YAZBEK', 'area': 'PRODUCCION', 'sexo': 'HOMBRE', 'edad': 22}, {'num_emp': 490, 'ap_pat': 'YEPIZ', 'ap,mat': 'YEPIZ', 'nombre': 'YAZBEK', 'area': 'OFICINA', 'sexo': 'HOMBRE', 'edad': 43}, {'num_emp': 8, 'ap_pat': 'GAYNOR', 'ap,mat': 'ROMERO', 'nombre': 'PEDRO', 'area': 'SUPERVISOR', 'sexo': 'HOMBRE', 'edad': 64}, {'num_emp': 358, 'ap_pat': 'MAVRIRIS', 'ap,mat': 'GAYNOR', 'nombre': 'PEDRO', 'area': 'ALMACEN', 'sexo': 'HOMBRE', 'edad': 60}]

In [55]:
salida=pd.DataFrame(lista)
salida

    num_emp    ap_pat    ap,mat    nombre        area    sexo  edad
0        16   SANCHEZ    GAYNOR  GILBERTO     ALMACEN  HOMBRE    28
1       322   SANCHEZ   KHALIFA     PAULO          QA  HOMBRE    60
2       183    ROMERO   KHALIFA  GILBERTO     GERENTE  HOMBRE    31
3       252    FLORES  MAVRIRIS   EMANUEL     ALMACEN  HOMBRE    25
4       353    GAYNOR   MORALES    YAZBEK     GERENTE  HOMBRE    50
5        78     MARIN    GARCIA     OSCAR     GERENTE  HOMBRE    43
6        24    GAYNOR     YEPIZ     PEDRO     OFICINA  HOMBRE    27
7       367     YEPIZ    GAYNOR   MANUELA    SISTEMAS   MUJER    39
8       275    GARCIA    GAYNOR    KARINA    SISTEMAS   MUJER    40
9        39   MORALES     MARIN   EMANUEL          QA  HOMBRE    62
10       38   KHALIFA     MARIN   CARLOTA  SUPERVISOR   MUJER    19
11       51    FLORES   SANCHEZ   CARLOTA    SISTEMAS   MUJER    18
12      163   KHALIFA    GARCIA    MARTIN  SUPERVISOR  HOMBRE    57
13        4   BARBOSA   BARBOSA   MANUELA  PRODUCCION   MUJER    34
14      197  MAVRIRIS   SANCHEZ     PEDRO     GERENTE  HOMBRE    41
15      205     YEPIZ   MORALES     PETRA  PRODUCCION   MUJER    20
16       70     MARIN    ROMERO     PAULO          QA  HOMBRE    54
17      346   SANCHEZ    GARCIA    CARLOS     GERENTE  HOMBRE    38
18       64   MORALES   SANCHEZ   MANUELA          QA   MUJER    57
19      380    GARCIA    GARCIA    CARLOS  SUPERVISOR  HOMBRE    54
20      132   MORALES   BARBOSA  PAUILINA  SUPERVISOR   MUJER    20
21       39   BARBOSA  MAVRIRIS   CARLOTA     ALMACEN   MUJER    27
22       30  MAVRIRIS   MORALES    KARINA    SISTEMAS   MUJER    22
23      222   SANCHEZ    FLORES    CARLOS     OFICINA  HOMBRE    26
24      146   SANCHEZ     YEPIZ     PETRA  SUPERVISOR   MUJER    45
25      131   MORALES   BARBOSA   CARLOTA     OFICINA   MUJER    42
26       87     MARIN   SANCHEZ    CARLOS  SUPERVISOR  HOMBRE    37
27       27   SANCHEZ     YEPIZ   MANUELA          QA   MUJER    53
28      321   KHALIFA  MAVRIRIS     PETRA  SUPERVISOR   MUJER    27
29      125  MAVRIRIS   KHALIFA  GILBERTO  PRODUCCION  HOMBRE    59
30      154    ROMERO    GAYNOR     OSCAR          QA  HOMBRE    57
31      281  MAVRIRIS   BARBOSA   MANUELA     GERENTE   MUJER    46
32      396     MARIN    GAYNOR     OSCAR    SISTEMAS  HOMBRE    37
33      358    ROMERO   KHALIFA  GILBERTO     ALMACEN  HOMBRE    37
34      284    GAYNOR   BARBOSA     OSCAR     OFICINA  HOMBRE    30
35      176   KHALIFA   SANCHEZ     OSCAR     ALMACEN  HOMBRE    50
36      339    GARCIA    GARCIA   MANUELA  PRODUCCION   MUJER    23
37      201  MAVRIRIS     MARIN    MARTIN  SUPERVISOR  HOMBRE    39
38      306    GARCIA   KHALIFA    YAZBEK    SISTEMAS  HOMBRE    37
39      403    GAYNOR    FLORES     OSCAR     ALMACEN  HOMBRE    60
40      154  MAVRIRIS    ROMERO    CARLOS     GERENTE  HOMBRE    44
41      224   MORALES   SANCHEZ    KARINA  PRODUCCION   MUJER    54
42      411    FLORES     YEPIZ    KARINA    SISTEMAS   MUJER    35
43      124   MORALES     YEPIZ     OSCAR     GERENTE  HOMBRE    50
44      216     YEPIZ   MORALES   CARLOTA     ALMACEN   MUJER    52
45      207     YEPIZ   SANCHEZ    MARTIN     GERENTE  HOMBRE    50
46       35     MARIN     MARIN    CARLOS  SUPERVISOR  HOMBRE    55
47      241     YEPIZ    ROMERO   MANUELA  PRODUCCION   MUJER    38
48      397     MARIN   KHALIFA     PEDRO     GERENTE  HOMBRE    28
49      161  MAVRIRIS    GAYNOR   MANUELA  SUPERVISOR   MUJER    31
50      423    GAYNOR    FLORES   EMANUEL     OFICINA  HOMBRE    38
51      206  MAVRIRIS    ROMERO    CARLOS          QA  HOMBRE    22
52      425    FLORES   KHALIFA    CARLOS  SUPERVISOR  HOMBRE    62
53       57   SANCHEZ    FLORES   EMANUEL     OFICINA  HOMBRE    40
54      497   KHALIFA     YEPIZ  GILBERTO     ALMACEN  HOMBRE    32
55       25   MORALES     YEPIZ    MARTIN          QA  HOMBRE    61
56      203   SANCHEZ     MARIN    YAZBEK  PRODUCCION  HOMBRE    22
57      490     YEPIZ     YEPIZ    YAZBEK     OFICINA  HOMBRE    43
58        8    GAYNOR    ROMERO     PEDRO  SUPERVISOR  HOMBRE    64
59      358  MAVRIRIS    GAYNOR     PEDRO     ALMACEN  HOMBRE    60

In [54]:
x=(yaml.dump(lista, sort_keys=False, default_flow_style=False))
print (x)

- num_emp: 16
  ap_pat: SANCHEZ
  ap,mat: GAYNOR
  nombre: GILBERTO
  area: ALMACEN
  sexo: HOMBRE
  edad: 28
- num_emp: 322
  ap_pat: SANCHEZ
  ap,mat: KHALIFA
  nombre: PAULO
  area: QA
  sexo: HOMBRE
  edad: 60
- num_emp: 183
  ap_pat: ROMERO
  ap,mat: KHALIFA
  nombre: GILBERTO
  area: GERENTE
  sexo: HOMBRE
  edad: 31
- num_emp: 252
  ap_pat: FLORES
  ap,mat: MAVRIRIS
  nombre: EMANUEL
  area: ALMACEN
  sexo: HOMBRE
  edad: 25
- num_emp: 353
  ap_pat: GAYNOR
  ap,mat: MORALES
  nombre: YAZBEK
  area: GERENTE
  sexo: HOMBRE
  edad: 50
- num_emp: 78
  ap_pat: MARIN
  ap,mat: GARCIA
  nombre: OSCAR
  area: GERENTE
  sexo: HOMBRE
  edad: 43
- num_emp: 24
  ap_pat: GAYNOR
  ap,mat: YEPIZ
  nombre: PEDRO
  area: OFICINA
  sexo: HOMBRE
  edad: 27
- num_emp: 367
  ap_pat: YEPIZ
  ap,mat: GAYNOR
  nombre: MANUELA
  area: SISTEMAS
  sexo: MUJER
  edad: 39
- num_emp: 275
  ap_pat: GARCIA
  ap,mat: GAYNOR
  nombre: KARINA
  area: SISTEMAS
  sexo: MUJER
  edad: 40
- num_emp: 39
  ap_pat: MORALES
  ap,mat: MARIN
  nombre: EMANUEL
  area: QA
  sexo: HOMBRE
  edad: 62
- num_emp: 38
  ap_pat: KHALIFA
  ap,mat: MARIN
  nombre: CARLOTA
  area: SUPERVISOR
  sexo: MUJER
  edad: 19
- num_emp: 51
  ap_pat: FLORES
  ap,mat: SANCHEZ
  nombre: CARLOTA
  area: SISTEMAS
  sexo: MUJER
  edad: 18
- num_emp: 163
  ap_pat: KHALIFA
  ap,mat: GARCIA
  nombre: MARTIN
  area: SUPERVISOR
  sexo: HOMBRE
  edad: 57
- num_emp: 4
  ap_pat: BARBOSA
  ap,mat: BARBOSA
  nombre: MANUELA
  area: PRODUCCION
  sexo: MUJER
  edad: 34
- num_emp: 197
  ap_pat: MAVRIRIS
  ap,mat: SANCHEZ
  nombre: PEDRO
  area: GERENTE
  sexo: HOMBRE
  edad: 41
- num_emp: 205
  ap_pat: YEPIZ
  ap,mat: MORALES
  nombre: PETRA
  area: PRODUCCION
  sexo: MUJER
  edad: 20
- num_emp: 70
  ap_pat: MARIN
  ap,mat: ROMERO
  nombre: PAULO
  area: QA
  sexo: HOMBRE
  edad: 54
- num_emp: 346
  ap_pat: SANCHEZ
  ap,mat: GARCIA
  nombre: CARLOS
  area: GERENTE
  sexo: HOMBRE
  edad: 38
- num_emp: 64
  ap_pat: MORALES
  ap,mat: SANCHEZ
  nombre: MANUELA
  area: QA
  sexo: MUJER
  edad: 57
- num_emp: 380
  ap_pat: GARCIA
  ap,mat: GARCIA
  nombre: CARLOS
  area: SUPERVISOR
  sexo: HOMBRE
  edad: 54
- num_emp: 132
  ap_pat: MORALES
  ap,mat: BARBOSA
  nombre: PAUILINA
  area: SUPERVISOR
  sexo: MUJER
  edad: 20
- num_emp: 39
  ap_pat: BARBOSA
  ap,mat: MAVRIRIS
  nombre: CARLOTA
  area: ALMACEN
  sexo: MUJER
  edad: 27
- num_emp: 30
  ap_pat: MAVRIRIS
  ap,mat: MORALES
  nombre: KARINA
  area: SISTEMAS
  sexo: MUJER
  edad: 22
- num_emp: 222
  ap_pat: SANCHEZ
  ap,mat: FLORES
  nombre: CARLOS
  area: OFICINA
  sexo: HOMBRE
  edad: 26
- num_emp: 146
  ap_pat: SANCHEZ
  ap,mat: YEPIZ
  nombre: PETRA
  area: SUPERVISOR
  sexo: MUJER
  edad: 45
- num_emp: 131
  ap_pat: MORALES
  ap,mat: BARBOSA
  nombre: CARLOTA
  area: OFICINA
  sexo: MUJER
  edad: 42
- num_emp: 87
  ap_pat: MARIN
  ap,mat: SANCHEZ
  nombre: CARLOS
  area: SUPERVISOR
  sexo: HOMBRE
  edad: 37
- num_emp: 27
  ap_pat: SANCHEZ
  ap,mat: YEPIZ
  nombre: MANUELA
  area: QA
  sexo: MUJER
  edad: 53
- num_emp: 321
  ap_pat: KHALIFA
  ap,mat: MAVRIRIS
  nombre: PETRA
  area: SUPERVISOR
  sexo: MUJER
  edad: 27
- num_emp: 125
  ap_pat: MAVRIRIS
  ap,mat: KHALIFA
  nombre: GILBERTO
  area: PRODUCCION
  sexo: HOMBRE
  edad: 59
- num_emp: 154
  ap_pat: ROMERO
  ap,mat: GAYNOR
  nombre: OSCAR
  area: QA
  sexo: HOMBRE
  edad: 57
- num_emp: 281
  ap_pat: MAVRIRIS
  ap,mat: BARBOSA
  nombre: MANUELA
  area: GERENTE
  sexo: MUJER
  edad: 46
- num_emp: 396
  ap_pat: MARIN
  ap,mat: GAYNOR
  nombre: OSCAR
  area: SISTEMAS
  sexo: HOMBRE
  edad: 37
- num_emp: 358
  ap_pat: ROMERO
  ap,mat: KHALIFA
  nombre: GILBERTO
  area: ALMACEN
  sexo: HOMBRE
  edad: 37
- num_emp: 284
  ap_pat: GAYNOR
  ap,mat: BARBOSA
  nombre: OSCAR
  area: OFICINA
  sexo: HOMBRE
  edad: 30
- num_emp: 176
  ap_pat: KHALIFA
  ap,mat: SANCHEZ
  nombre: OSCAR
  area: ALMACEN
  sexo: HOMBRE
  edad: 50
- num_emp: 339
  ap_pat: GARCIA
  ap,mat: GARCIA
  nombre: MANUELA
  area: PRODUCCION
  sexo: MUJER
  edad: 23
- num_emp: 201
  ap_pat: MAVRIRIS
  ap,mat: MARIN
  nombre: MARTIN
  area: SUPERVISOR
  sexo: HOMBRE
  edad: 39
- num_emp: 306
  ap_pat: GARCIA
  ap,mat: KHALIFA
  nombre: YAZBEK
  area: SISTEMAS
  sexo: HOMBRE
  edad: 37
- num_emp: 403
  ap_pat: GAYNOR
  ap,mat: FLORES
  nombre: OSCAR
  area: ALMACEN
  sexo: HOMBRE
  edad: 60
- num_emp: 154
  ap_pat: MAVRIRIS
  ap,mat: ROMERO
  nombre: CARLOS
  area: GERENTE
  sexo: HOMBRE
  edad: 44
- num_emp: 224
  ap_pat: MORALES
  ap,mat: SANCHEZ
  nombre: KARINA
  area: PRODUCCION
  sexo: MUJER
  edad: 54
- num_emp: 411
  ap_pat: FLORES
  ap,mat: YEPIZ
  nombre: KARINA
  area: SISTEMAS
  sexo: MUJER
  edad: 35
- num_emp: 124
  ap_pat: MORALES
  ap,mat: YEPIZ
  nombre: OSCAR
  area: GERENTE
  sexo: HOMBRE
  edad: 50
- num_emp: 216
  ap_pat: YEPIZ
  ap,mat: MORALES
  nombre: CARLOTA
  area: ALMACEN
  sexo: MUJER
  edad: 52
- num_emp: 207
  ap_pat: YEPIZ
  ap,mat: SANCHEZ
  nombre: MARTIN
  area: GERENTE
  sexo: HOMBRE
  edad: 50
- num_emp: 35
  ap_pat: MARIN
  ap,mat: MARIN
  nombre: CARLOS
  area: SUPERVISOR
  sexo: HOMBRE
  edad: 55
- num_emp: 241
  ap_pat: YEPIZ
  ap,mat: ROMERO
  nombre: MANUELA
  area: PRODUCCION
  sexo: MUJER
  edad: 38
- num_emp: 397
  ap_pat: MARIN
  ap,mat: KHALIFA
  nombre: PEDRO
  area: GERENTE
  sexo: HOMBRE
  edad: 28
- num_emp: 161
  ap_pat: MAVRIRIS
  ap,mat: GAYNOR
  nombre: MANUELA
  area: SUPERVISOR
  sexo: MUJER
  edad: 31
- num_emp: 423
  ap_pat: GAYNOR
  ap,mat: FLORES
  nombre: EMANUEL
  area: OFICINA
  sexo: HOMBRE
  edad: 38
- num_emp: 206
  ap_pat: MAVRIRIS
  ap,mat: ROMERO
  nombre: CARLOS
  area: QA
  sexo: HOMBRE
  edad: 22
- num_emp: 425
  ap_pat: FLORES
  ap,mat: KHALIFA
  nombre: CARLOS
  area: SUPERVISOR
  sexo: HOMBRE
  edad: 62
- num_emp: 57
  ap_pat: SANCHEZ
  ap,mat: FLORES
  nombre: EMANUEL
  area: OFICINA
  sexo: HOMBRE
  edad: 40
- num_emp: 497
  ap_pat: KHALIFA
  ap,mat: YEPIZ
  nombre: GILBERTO
  area: ALMACEN
  sexo: HOMBRE
  edad: 32
- num_emp: 25
  ap_pat: MORALES
  ap,mat: YEPIZ
  nombre: MARTIN
  area: QA
  sexo: HOMBRE
  edad: 61
- num_emp: 203
  ap_pat: SANCHEZ
  ap,mat: MARIN
  nombre: YAZBEK
  area: PRODUCCION
  sexo: HOMBRE
  edad: 22
- num_emp: 490
  ap_pat: YEPIZ
  ap,mat: YEPIZ
  nombre: YAZBEK
  area: OFICINA
  sexo: HOMBRE
  edad: 43
- num_emp: 8
  ap_pat: GAYNOR
  ap,mat: ROMERO
  nombre: PEDRO
  area: SUPERVISOR
  sexo: HOMBRE
  edad: 64
- num_emp: 358
  ap_pat: MAVRIRIS
  ap,mat: GAYNOR
  nombre: PEDRO
  area: ALMACEN
  sexo: HOMBRE
  edad: 60